# pipeline as a code for deploying IAC 
# any other CI/CD tool like jenkins, gitlab etc can also be used

trigger: 
- main


pool:
  vmImage: ubuntu-latest


variables:
  configuration: debug
  platform: x64

steps:
- script: echo Hello, K8s!
  displayName: 'Running a K8s cluster pipeline'




- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'CognitiveSubscription'
    backendAzureRmResourceGroupName: 'POC'
    backendAzureRmStorageAccountName: 'cloudcoverstorage'
    backendAzureRmContainerName: 'terraformcontainer'
    backendAzureRmKey: 'terraform.tfstate'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'CognitiveSubscription'

# - task: TerraformTaskV3@3
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     environmentServiceNameAzureRM: 'CognitiveSubscription'
     
    
# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'CognitiveSubscription'
#     azureResourceGroup: $(azureResourceGroup)
#     kubernetesCluster: $(kubernetesCluster)
#     command: 'apply'
#     arguments: -f $(System.DefaultWorkingDirectory)/manifest-info.yml
#   displayName: 'Apply kubernetes manifest'  

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    environmentServiceNameAzureRM: 'CognitiveSubscription'





     
# - task: CmdLine@2
#   inputs:
#      script: |
#        echo  $(azureResourceGroup)
#        echo  $(kubernetesCluster)
#        echo Hello world


# devSecOps sarif tool
  
- task: Gitleaks@2
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'predefined'
    predefinedconfigfile: 'GitleaksUdmCombo.toml'
    reportformat: 'sarif'

