# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'CognitiveSubscription (95e910f9-7fcb-4fb8-90a1-d81f3d52cfa9)'
    backendAzureRmResourceGroupName: 'POC'
    backendAzureRmStorageAccountName: 'cloudcoverstorage'
    backendAzureRmContainerName: 'terraformcontainer'
    backendAzureRmKey: 'terraform.tftstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'CognitiveSubscription (95e910f9-7fcb-4fb8-90a1-d81f3d52cfa9)'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'CognitiveSubscription (95e910f9-7fcb-4fb8-90a1-d81f3d52cfa9)'
    backendAWSBucketName: 

# - task: TerraformTaskV3@3
#   inputs:
#     provider: 'azurerm'
#     command: 'destroy'
#     environmentServiceNameAzureRM: 'CognitiveSubscription (95e910f9-7fcb-4fb8-90a1-d81f3d52cfa9)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'CognitiveSubscription (95e910f9-7fcb-4fb8-90a1-d81f3d52cfa9)'
    scriptType: 'batch'
    inlineScript: |
      az aks get-credentials --resource-group "rg-demoaks" --name "aks-democluster-main" --admin
      kubectl apply -f $(System.DefaultWorkingDirectory)/manifest-info.yml
      
  displayName: 'Apply kubernetes manifest'